elearning/urls.py
from django.contrib import admin
from django.urls import path, include
from pages.views import about_view

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("courses.urls")),
    path("faq/", include("faq.urls")),
    path("about/", about_view, name="about"),
    path("student/", include("student.urls")),
]

faq/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.faq_list, name="faq_list"),
    path("my/", views.MyFAQListView.as_view(), name="my_faq_list"),
    path("create/", views.FAQCreateView.as_view(), name="faq_create"),
    path("<int:pk>/", views.faq_detail, name="faq_detail"),
    path("<int:pk>/edit/", views.FAQUpdateView.as_view(), name="faq_update"),
    path("<int:pk>/delete/", views.FAQDeleteView.as_view(), name="faq_delete"),
]

accounts/models.py
from django.conf import settings
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    SUBSCRIPTION_CHOICES = [
        ("free", "Сонирхогч"),
        ("student", "Сурагч"),
        ("teacher", "Багш"),
    ]

    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="profile",
    )
    profile_picture = models.URLField(
        blank=True,
        null=True,
    )
    bio = models.TextField(blank=True)
    phone_number = models.CharField(max_length=20, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    subscription_level = models.CharField(
        max_length=20,
        choices=SUBSCRIPTION_CHOICES,
        default="free",
    )
    social_links = models.TextField(
        blank=True,
    )

    def __str__(self):
        return f"Profile of {self.user.username}"


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def save_user_profile(sender, instance, **kwargs):
    if hasattr(instance, "profile"):
        instance.profile.save()

courses/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from .validators import validate_youtube_url


class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(unique=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Course(models.Model):
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="courses",
        null=True,
        blank=True,
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="courses",
    )

    title = models.CharField(max_length=200)
    image_url = models.URLField(blank=True)
    duration = models.CharField(max_length=100, blank=True)
    short_description = models.CharField(max_length=255, blank=True)
    description = models.TextField(blank=True)
    video_url = models.URLField(blank=True, validators=[validate_youtube_url],)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

templates/partials/footer.html
<footer class="py-4 mt-5 border-top bg-light">
  <div class="container d-flex flex-wrap justify-content-between align-items-center">

    <p class="mb-0 text-muted">
      © {{ now|date:"Y" }} Цахим сургалт
      <span class="d-none d-sm-inline">· 2025 он</span>
    </p>

    <a href="#"
       class="text-decoration-none text-muted small d-flex align-items-center">
      <span class="me-1">Дээш</span>
      ↑
    </a>

  </div>
</footer>

templates/partials/header.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/header.css' %}">
<header class="border-bottom">
  <nav class="navbar navbar-expand-lg navbar-dark shadow-sm navbar-clean">
    <div class="container">

      <a class="navbar-brand d-flex align-items-center" href="{% url 'course_list' %}">
        <img src="{% static 'img/logo.svg' %}" alt="E-Learning Logo" style="height: 30px;" class="me-2">
      </a>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mainNavbar"
        aria-controls="mainNavbar" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="mainNavbar">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'course_list' %}">
              Онлайн сургалт
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'wish_list' %}">
              Сурагчын булан
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'faq_list' %}">
              Багшийн булан
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'profile_list' %}">
              Нийт гишүүд
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'about' %}">
              Бидний тухай
            </a>
          </li>
        </ul>

        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          {% if user.is_authenticated %}

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle d-flex align-items-center" href="#" id="userDropdown" role="button"
              data-bs-toggle="dropdown" aria-expanded="false">
              <div class="d-none d-md-flex flex-column user-chip">
                <span class="fw-semibold text-light"> Сайна уу {{ user.username }}</span>
              </div>
              <span class="d-md-none user-chip">
                {{ user.username }}
              </span>
            </a>
            <ul class="dropdown-menu dropdown-menu-end dropdown-menu-soft" aria-labelledby="userDropdown">
              <li>
                <a class="dropdown-item" href="{% url 'profile_detail' request.user.profile.pk %}">
                  Миний профайл
                </a>
              </li>
              <li>
                <a class="dropdown-item" href="{% url 'my_courses' %}">
                  Миний хичээл
                </a>
              </li>
              {% if user.is_staff %}
              <li>
                <hr class="dropdown-divider">
              </li>
              <li>
                <a class="dropdown-item" href="/admin/">
                  Django админ
                </a>
              </li>
              {% endif %}
            </ul>
          </li>

          <li class="nav-item ms-lg-3 mt-2 mt-lg-0">
            <form action="{% url 'logout' %}" method="post" class="d-inline">
              {% csrf_token %}
              <button type="submit" class="btn btn-sm btn-outline-light px-3">
                Гарах
              </button>
            </form>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">
              Нэвтрэх
            </a>
          </li>
          <li class="nav-item ms-lg-2 mt-2 mt-lg-0">
            <a class="btn btn-sm btn-outline-light px-3" href="{% url 'register' %}">
              Бүртгүүлэх
            </a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
</header>

templates/partials/slide.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/slide.css' %}">
<div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true"></button>
    <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1"></button>
  </div>

  <div class="carousel-inner">
    <!-- SLIDE 1 -->
    <div class="carousel-item active">
      <img src="https://www.studioenglish.com/wp-content/uploads/2021/05/How-to-Learn-English-by-Yourself-1_d.jpg" alt="Elearning slide" />

      <div class="container">
        <div class="carousel-caption text-start">
          <h1>Цахим сургалт</h1>
          <p class="opacity-75">
            Онлайн сургалт нэг дор цэгцтэйгээр үзэх.
          </p>
          <p><a class="btn btn-lg btn-primary" href="{% url 'faq_list' %}">Дэлгэрэнгүй</a></p>
        </div>
      </div>
    </div>

    <!-- SLIDE 2 -->
    <div class="carousel-item">
      <img src="https://www.ulc.com.sg/wp-content/uploads/2022/11/An-English-Language-School-In-Singapore-Recommends-The-Best-Songs-For-Learning-English-scaled.jpg" alt="Elearning slide 2" />

      <div class="container">
        <div class="carousel-caption text-end">
          <h1>Багш нар</h1>
          <p>Орчин үеийн програмчлалын технологийн онлайн сургалт.</p>
          <p><a class="btn btn-lg btn-primary" href="{% url 'profile_list' %}">Дэлгэрэнгүй</a></p>
        </div>
      </div>
    </div>
  </div>

  <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
    <span class="carousel-control-prev-icon"></span>
  </button>

  <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
    <span class="carousel-control-next-icon"></span>
  </button>
</div>

templates/partials/slide_detail.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/slide_detail.css' %}">
<div id="headerHero">
  <img src="https://www.shutterstock.com/image-illustration/grainy-background-blue-orange-red-260nw-2595295995.jpg" alt="Header Image">

  <div class="hero-caption">
    <h1>{{ title }}</h1>
    <p>Онлайн сургалтуудыг нэг дор цэгцтэйгээр үзэх.</p>
  </div>
</div>